version: "3"

services:
  database:
    container_name: appDb
    image: mongo
    volumes: 
      - data:/data/db
    environment: 
      - MONGO_DATA_DIR=/data/db
    ports:
      - "27017:27017"
  server:
    container_name: appServer
    build: .
    ports: 
      - "3000:3000"
    links:
      - database
    depends_on: 
      - database

volumes:
  data: